### ISSUE TITLE
MLP

### ISSUE THREAD

**Issue by DmitryKochetkov** [DmitryKochetkov/easyml#2]
# Description
Implement a multilayer perceptron.

# Tasks

- [ ] Create a module for downloading MNIST dataset.
- [ ] Create a module for layers
- [ ] Create a class for MLP
